# Site settings, Base config (overridden by the other configs)
# The config builds for localhost testing
url: "//localhost:4000"
author: "BlinkTrade"
baseurl: ""

exchange: "bitcoinvietnam"
exchange_logo: "bitcoinvietnam"

custom_css: "lightgreen"

twitter_widget_id: "717635114658873344"
twitter_widget_name: "vbtc_vietnam"
twitter_widget_theme: "dark"
twitter_widget_link_color: "#88DA65"

default_country_code: "EN"
blinktrade_broker_id: 3
required_level_to_be_a_pro_trader: 0

blinktrade_backend_api: "localhost"


# Build settings
markdown: kramdown

remittance_box: "{
  'BRL':[ ['BitStampUSD',        'USD', 'BITSTAMP_BTCUSD_BEST_BID / 100000000', 'BITSTAMP_BTCUSD_BEST_ASK / 100000000'  ],
          ['USD -> BTC -> BRL',  'BRL', 'BLINK_BTCBRL_BEST_BID /  BITSTAMP_BTCUSD_BEST_ASK', 'BLINK_BTCBRL_BEST_ASK /  BITSTAMP_BTCUSD_BEST_BID'  ],
          ['BRL -> BTC -> VEF',  'VEF', 'BLINK_BTCVEF_BEST_BID /  BLINK_BTCBRL_BEST_ASK',    'BLINK_BTCVEF_BEST_ASK /  BLINK_BTCBRL_BEST_BID' ],
          ['BRL -> BTC -> CLP',  'CLP', 'BLINK_BTCCLP_BEST_BID /  BLINK_BTCBRL_BEST_ASK', 'BLINK_BTCCLP_BEST_ASK /  BLINK_BTCBRL_BEST_BID'  ] ],
  'VEF':[ ['BitStampUSD',        'USD', 'BITSTAMP_BTCUSD_BEST_BID / 100000000', 'BITSTAMP_BTCUSD_BEST_ASK / 100000000'  ],
          ['USD -> BTC -> VEF',  'VEF', 'BLINK_BTCVEF_BEST_BID /  BITSTAMP_BTCUSD_BEST_ASK', 'BLINK_BTCVEF_BEST_ASK /  BITSTAMP_BTCUSD_BEST_BID' ] ,
          ['BRL -> BTC -> VEF',  'VEF', 'BLINK_BTCVEF_BEST_BID /  BLINK_BTCBRL_BEST_ASK',    'BLINK_BTCVEF_BEST_ASK /  BLINK_BTCBRL_BEST_BID' ],
          ['VEF -> BTC -> CLP',  'CLP', 'BLINK_BTCCLP_BEST_BID /  BLINK_BTCVEF_BEST_ASK',    'BLINK_BTCCLP_BEST_ASK /  BLINK_BTCVEF_BEST_BID' ] ],
  'CLP':[ ['BitStampUSD',        'USD', 'BITSTAMP_BTCUSD_BEST_BID / 100000000', 'BITSTAMP_BTCUSD_BEST_ASK / 100000000'  ],
          ['USD -> BTC -> CLP',  'CLP', 'BLINK_BTCCLP_BEST_BID /  BITSTAMP_BTCUSD_BEST_ASK', 'BLINK_BTCCLP_BEST_ASK /  BITSTAMP_BTCUSD_BEST_BID' ] ,
          ['BRL -> BTC -> CLP',  'CLP', 'BLINK_BTCCLP_BEST_BID /  BLINK_BTCBRL_BEST_ASK',    'BLINK_BTCCLP_BEST_ASK /  BLINK_BTCBRL_BEST_BID' ] ,
          ['VEF -> BTC -> CLP',  'CLP', 'BLINK_BTCCLP_BEST_BID /  BLINK_BTCVEF_BEST_ASK',    'BLINK_BTCCLP_BEST_ASK /  BLINK_BTCVEF_BEST_BID' ] ],
  'VND':[ ['BitStampUSD',        'USD', 'BITSTAMP_BTCUSD_BEST_BID / 100000000', 'BITSTAMP_BTCUSD_BEST_ASK / 100000000'  ],
          ['USD -> BTC -> VND',  'VND', 'BLINK_BTCVND_BEST_BID /  BITSTAMP_BTCUSD_BEST_ASK', 'BLINK_BTCVND_BEST_ASK /  BITSTAMP_BTCUSD_BEST_BID' ] ],
  'PKR':[ ['BitStampUSD',        'USD', 'BITSTAMP_BTCUSD_BEST_BID / 100000000', 'BITSTAMP_BTCUSD_BEST_ASK / 100000000'  ],
          ['USD -> BTC -> PKR',  'PKR', 'BLINK_BTCPKR_BEST_BID /  BITSTAMP_BTCUSD_BEST_ASK', 'BLINK_BTCPKR_BEST_ASK /  BITSTAMP_BTCUSD_BEST_BID' ] ]
  }"


symbol: "BTCVND"

languages: ["en_US", "vi", "es", "pt_BR", "ro", "zn_CN"]

video : 'true'
navbar: 'navbar-inverse'
phrases: [phrase1, phrase2, phrase4]

exclude: [
  ".bundle",
  ".sass-cache",
  ".idea",
  "jsdev",
  "themes/ander",
  "vendor",
  ".ruby-version",
  "build_and_deploy_beta.sh",
  "build_and_deploy_mainnet.sh",
  "build_and_deploy_signet.sh",
  "build_and_run_localhost.sh",
  "build_javascript.sh",
  "build_site.sh",
  "config.rb",
  "deploy_site.sh",
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md",
  "run_site.sh"
]
source: .
destination: ./_site_localhost
plugins_dir: ./_plugins
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "post/page:num"
permalink: /post/:title/
facebook: https://www.facebook.com/VBTC.vn
twitter: https://twitter.com/vbtc_vietnam
youtube: https://www.youtube.com/user/BitcoinVietnam/videos

sass:
  sass_dir: assets/themes/coinage/sass
  style: compressed
